# Generated by Django 4.1.7 on 2023-05-20 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/default.jpg')),
                ('slug', models.SlugField(default='')),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
