# Generated by Django 4.1.7 on 2023-05-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(related_name='courses', to='courses.subject'),
        ),
    ]
