# Generated by Django 4.1.7 on 2023-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subject_alter_course_image_course_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='path_and_rename'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='path_and_rename'),
        ),
    ]
