# Generated by Django 4.1.7 on 2023-05-20 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
