# Generated by Django 4.1.7 on 2023-05-20 09:37

import ckeditor_uploader.fields
import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=courses.models.Course.path_and_rename),
        ),
        migrations.AlterField(
            model_name='course',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to=courses.models.Subject.path_and_rename),
        ),
    ]
