# Generated by Django 4.1.7 on 2023-12-25 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_keywords',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='seo_meta_desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
    ]
