# Generated by Django 4.1.7 on 2023-12-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_seo_keywords_course_seo_meta_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seo_meta_desc',
        ),
    ]
