# Generated by Django 4.1.7 on 2023-12-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_meta_desc',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
