# Generated by Django 4.1.7 on 2023-12-26 11:28

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_seo_keywords_course_seo_meta_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=80)),
                ('course_name', models.CharField(max_length=255)),
                ('ref_id', models.CharField(max_length=20)),
                ('certificate', models.FileField(default='certificate/certificate.png', upload_to=courses.models.Certificate.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
